apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-hello-world-deployment-deneme
  labels:
    app: nginx-deneme
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-deneme
  template:
    metadata:
      labels:
        app: nginx-deneme
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        # image: brndnmtthws/nginx-echo-headers
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: argocd-hello-world-service-deneme
spec:
  selector:
    app: nginx-deneme
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-hello-world-ingress-deneme
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
    - host: argocd-hello-world-deneme.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: argocd-hello-world-service-deneme
                port:
                  number: 80
