apiVersion: apps/v1
kind: Deployment
metadata:
  name: wp-app-deployment
  labels:
    app: wp-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wp-app
  template:
    metadata:
      labels:
        app: wp-app
    spec:
      containers:
      - name: wp-app
        image: codeexplore8080/wp
        ports:
        - containerPort: 8080
        env:
        - name: WORDPRESS_DATABASE_HOST
          value: wp-db
        - name: WORDPRESS_DATABASE_NAME
          value: my_database
        - name: WORDPRESS_DATABASE_USER
          value: root
        - name: WORDPRESS_DATABASE_PASSWORD
          value: mA()()19861991root
